### ISSUE TITLE
Debug message loss/routing issues

### ISSUE THREAD

**Issue by Skraelinger** [Skraelinger/AzureIoT_LoRaWan_StarterKit#13]

**Comment by bart-jansen** [comment]
Fixed issue, was probably due to wrong routing setup in IoT Edge.. Got it working by adding this route:
 `"visualizerRoute": "FROM /* INTO BrokeredEndpoint(\"/modules/logs-visualizer/inputs/input1\")"`

**Comment by Skraelinger** [comment]
Temporary workaround (socket vs. IoT Edge routing) needs to be removed and root cause identified and addressed.

**Comment by Skraelinger** [comment]
Still requires testing--IoT Edge v2 shipped, we need to test on v2.
