### ISSUE TITLE
Predefined Edge Container: LoRaWAN Network Server

### ISSUE THREAD

**Issue by Skraelinger** [Skraelinger/AzureIoT_LoRaWan_StarterKit#23]
ARM/RPi initially

**Comment by kaizimmerm** [comment]
Repo (docker hub)

**Comment by Mandur** [comment]
@ronniesa fixed by #60 ? Working also with x86?

**Comment by ronniesa** [comment]
Yes, it is just not pushed on the docker hub view that we don't have yet an auto deploy with Intel. But the repo contains a working and testing docker for Intel
