### ISSUE TITLE
Debug process control issues

### ISSUE THREAD

**Issue by Skraelinger** [Skraelinger/AzureIoT_LoRaWan_StarterKit#4]

**Comment by PaulDFoster** [comment]
I wish to gather process telemetry to achieve a watch dog on the process.
Initial process control issues where caused by the module twin JSON update to the config file breaking the config file format, thus preventing the packet forwarder from running.

**Comment by PaulDFoster** [comment]
Corrected JSON update to retain global_conf.json structure after update.
