### ISSUE TITLE
Write Test Protocol for Arduino

### ISSUE THREAD

**Issue by Mandur** [Skraelinger/AzureIoT_LoRaWan_StarterKit#48]
1. 
- Send a c2d message
- Join
- confirm data up (conf down with c2d)
 
2. DataUpC2D
- Join
- confirm data up
- wiat 5
- confirm data up
- wait 5
- confirm data up
- Send a c2d message
- wait 5
- confirm data up (conf down with c2d)
 
3.
- Send a c2d message
- Join
- unconfirm data up (conf down with c2d)
 
4.
- Join
- unconfirm data up
- wiat 5
- unconfirm data up
- wait 5
- unconfirm data up
- Send a c2d message
- wait 5
- unconfirm data up (conf down with c2d)

**Comment by kaizimmerm** [comment]
Publish Arduino files in repo

**Comment by Mandur** [comment]
@ronniesa 
fixed by #76 , #57 , #69

**Comment by ronniesa** [comment]
yes, we may open a new item for the automated one but the TestCases.ino contains a first good run
