### ISSUE TITLE
Generalize file config structure

### ISSUE THREAD

**Issue by Skraelinger** [Skraelinger/AzureIoT_LoRaWan_StarterKit#5]

**Comment by PaulDFoster** [comment]
Plan is not to parse JSON but deliver supplied JSON string directly to the config file.

Issue: Module Twin does not support JSON Array, which breaks the config file format. Many server endpoints are defined in a JSON array in the confg file.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format

**Comment by PaulDFoster** [comment]
No resolution for Module Twin not supporting JSON array. However, other property modifications work for the gateway_conf section of global_conf.json files.
