### ISSUE TITLE
Initial JSON structure for telemetry

### ISSUE THREAD

**Issue by Skraelinger** [Skraelinger/AzureIoT_LoRaWan_StarterKit#7]
Create JSON payload to contain all information that we need send upstream with telemetry
1.	Original raw data
2.	Data decrypted
3.	Data decoded
4.	Gateway metadata (Data rate, Signal strength, Source GW address, GW GPS coordinates, etc.)

**Comment by kaizimmerm** [comment]
#41

**Comment by kaizimmerm** [comment]
#41
